# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32fb16de5c1208e57e6764c56553cbeb9f0cdff6fefbb172af2400d64eb64a62053e045efa10f4c26d1e3d21b351097748293bf8af0ff3a3af507e0bbaf8aa46

test:
  secret_key_base: 41b6b63f29b43b3b56d325281dbc3a1a2cd5980eb5267ee2656158ea373f45fb6a6ee3b494b33de47483863d8f568a06c60548de2333262a4e00f1767f4ad509

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
